import React, { useState } from 'react';

export default function MobileHIPAAPortal() {
  const [currentUser, setCurrentUser] = useState(null);
  const [activeTab, setActiveTab] = useState('dashboard');
  const [notifications, setNotifications] = useState([]);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [sessionInput, setSessionInput] = useState('');
  const [aiNotes, setAiNotes] = useState('');
  const [isGeneratingNotes, setIsGeneratingNotes] = useState(false);

  // Simple icons
  const MenuIcon = () => (
    <svg width="24" height="24" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
    </svg>
  );

  const BellIcon = () => (
    <svg width="24" height="24" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
    </svg>
  );

  const UserIcon = () => (
    <svg width="24" height="24" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
    </svg>
  );

  const testNotifications = () => {
    const email = {
      id: Date.now(),
      type: 'email',
      message: 'Test email sent to Test Patient',
      time: 'Just now'
    };
    const sms = {
      id: Date.now() + 1,
      type: 'sms', 
      message: 'Test SMS sent to Test Patient',
      time: 'Just now'
    };
    setNotifications(prev => [email, sms, ...prev]);
    alert('Test notifications added!');
  };

  const generateAIClinalNotes = async (sessionData) => {
    if (!sessionData.trim()) return;
    
    setIsGeneratingNotes(true);
    
    // Simulate AI processing
    setTimeout(() => {
      const mockNotes = `CLINICAL SESSION NOTES
Generated: ${new Date().toLocaleString()}

SUBJECTIVE:
Patient reported: "${sessionData}"

Key themes identified:
- Client engagement and therapeutic rapport
- Progress toward treatment goals
- Current emotional state and coping strategies

OBJECTIVE:
- Client appeared alert and oriented
- Appropriate mood and affect for session context
- Good eye contact and verbal communication
- Engaged actively in therapeutic process

ASSESSMENT:
- Client demonstrates continued progress in therapy
- Therapeutic alliance remains strong
- Treatment goals being addressed appropriately
- No immediate safety concerns identified

PLAN:
- Continue current therapeutic approach
- Schedule follow-up session as planned
- Consider adjusting treatment plan based on session outcomes
- Monitor progress toward established goals

CLINICIAN NOTES:
Session productive with good client engagement. Recommend continuing current treatment modalities.

---
Generated by Claude AI Assistant for ${currentUser?.name || 'Clinician'}
HIPAA Compliant - Confidential Medical Record`;

      setAiNotes(mockNotes);
      setIsGeneratingNotes(false);
    }, 2000);
  };

  const downloadNotes = (notes, filename) => {
    const blob = new Blob([notes], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename || `clinical-notes-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Login Screen
  if (!currentUser) {
    return (
      <div style={{
        minHeight: '100vh',
        background: 'linear-gradient(135deg, #dbeafe 0%, #e0e7ff 100%)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '16px',
        fontFamily: 'system-ui, sans-serif'
      }}>
        <div style={{width: '100%', maxWidth: '400px'}}>
          <div style={{
            backgroundColor: 'white',
            borderRadius: '16px',
            boxShadow: '0 10px 25px rgba(0,0,0,0.1)',
            padding: '32px',
            textAlign: 'center'
          }}>
            <h1 style={{fontSize: '24px', fontWeight: 'bold', marginBottom: '8px'}}>HIPAA Portal</h1>
            <p style={{color: '#666', marginBottom: '32px'}}>Secure Practice Management</p>
            
            <button
              onClick={() => setCurrentUser({role: 'therapist', name: 'Dr. Smith'})}
              style={{
                width: '100%',
                padding: '16px',
                backgroundColor: '#2563eb',
                color: 'white',
                border: 'none',
                borderRadius: '12px',
                fontSize: '16px',
                fontWeight: '600',
                marginBottom: '16px',
                cursor: 'pointer'
              }}
            >
              👨‍⚕️ Login as Therapist
            </button>
            
            <button
              onClick={() => setCurrentUser({role: 'client', name: 'Patient'})}
              style={{
                width: '100%',
                padding: '16px',
                backgroundColor: '#16a34a',
                color: 'white',
                border: 'none',
                borderRadius: '12px',
                fontSize: '16px',
                fontWeight: '600',
                cursor: 'pointer'
              }}
            >
              👤 Login as Client
            </button>
          </div>
        </div>
      </div>
    );
  }

  // Main Portal
  return (
    <div style={{minHeight: '100vh', backgroundColor: '#f9fafb', fontFamily: 'system-ui, sans-serif'}}>
      {/* Header */}
      <div style={{
        backgroundColor: 'white',
        padding: '16px',
        borderBottom: '1px solid #e5e7eb',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between'
      }}>
        <div style={{display: 'flex', alignItems: 'center', gap: '12px'}}>
          <button
            onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
            style={{padding: '8px', border: 'none', background: 'none', cursor: 'pointer'}}
          >
            <MenuIcon />
          </button>
          <div>
            <h1 style={{fontSize: '18px', fontWeight: '600', margin: 0}}>HIPAA Portal</h1>
            <p style={{fontSize: '14px', color: '#666', margin: 0}}>{currentUser.name}</p>
          </div>
        </div>
        <div style={{display: 'flex', alignItems: 'center', gap: '8px'}}>
          <button
            onClick={() => setActiveTab('notifications')}
            style={{
              padding: '8px',
              border: 'none',
              background: 'none',
              cursor: 'pointer',
              position: 'relative'
            }}
          >
            <BellIcon />
            {notifications.length > 0 && (
              <span style={{
                position: 'absolute',
                top: '0',
                right: '0',
                backgroundColor: '#ef4444',
                color: 'white',
                borderRadius: '50%',
                width: '18px',
                height: '18px',
                fontSize: '12px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center'
              }}>
                {notifications.length}
              </span>
            )}
          </button>
          <button
            onClick={() => setCurrentUser(null)}
            style={{padding: '8px', border: 'none', background: 'none', cursor: 'pointer'}}
          >
            <UserIcon />
          </button>
        </div>
      </div>

      {/* Content */}
      <div style={{padding: '16px', paddingBottom: '80px'}}>
        {activeTab === 'dashboard' && (
          <div>
            <h2 style={{fontSize: '20px', fontWeight: 'bold', marginBottom: '16px'}}>Dashboard</h2>
            
            <div style={{
              backgroundColor: 'white',
              borderRadius: '12px',
              padding: '16px',
              marginBottom: '16px',
              boxShadow: '0 2px 4px rgba(0,0,0,0.1)'
            }}>
              <h3 style={{marginBottom: '12px'}}>Quick Actions</h3>
              <button
                onClick={testNotifications}
                style={{
                  width: '100%',
                  padding: '12px',
                  backgroundColor: '#8b5cf6',
                  color: 'white',
                  border: 'none',
                  borderRadius: '8px',
                  fontSize: '16px',
                  fontWeight: '600',
                  cursor: 'pointer',
                  marginBottom: '8px'
                }}
              >
                🧪 Test Notification System
              </button>
              
              <button
                onClick={() => setActiveTab('ai-notes')}
                style={{
                  width: '100%',
                  padding: '12px',
                  backgroundColor: '#2563eb',
                  color: 'white',
                  border: 'none',
                  borderRadius: '8px',
                  fontSize: '16px',
                  fontWeight: '600',
                  cursor: 'pointer'
                }}
              >
                🤖 Try AI Clinical Notes
              </button>
            </div>
          </div>
        )}

        {activeTab === 'ai-notes' && (
          <div>
            <h2 style={{fontSize: '20px', fontWeight: 'bold', marginBottom: '16px'}}>
              🤖 AI Clinical Notes
            </h2>
            
            {/* Session Recording */}
            <div style={{
              backgroundColor: 'white',
              borderRadius: '12px',
              padding: '16px',
              marginBottom: '16px',
              boxShadow: '0 2px 4px rgba(0,0,0,0.1)'
            }}>
              <h3 style={{color: '#dc2626', marginBottom: '12px'}}>🎙️ Session Recording</h3>
              <p style={{fontSize: '14px', color: '#666', marginBottom: '16px'}}>
                Record entire therapy sessions. AI will generate comprehensive clinical notes.
              </p>
              
              <button
                onClick={() => alert('Session recording feature - would start recording here!')}
                style={{
                  width: '100%',
                  padding: '16px',
                  backgroundColor: '#dc2626',
                  color: 'white',
                  border: 'none',
                  borderRadius: '12px',
                  fontSize: '18px',
                  fontWeight: '700',
                  cursor: 'pointer'
                }}
              >
                🔴 START SESSION RECORDING
              </button>
            </div>

            {/* Session Notes Input */}
            <div style={{
              backgroundColor: 'white',
              borderRadius: '12px',
              padding: '16px',
              marginBottom: '16px',
              boxShadow: '0 2px 4px rgba(0,0,0,0.1)'
            }}>
              <h3 style={{marginBottom: '12px'}}>📝 Session Notes</h3>
              <textarea
                value={sessionInput}
                onChange={(e) => setSessionInput(e.target.value)}
                placeholder="Enter session notes, key observations, client interactions..."
                style={{
                  width: '100%',
                  height: '120px',
                  padding: '12px',
                  border: '1px solid #d1d5db',
                  borderRadius: '8px',
                  fontSize: '16px',
                  marginBottom: '12px',
                  boxSizing: 'border-box',
                  resize: 'vertical'
                }}
              />
              
              <div style={{display: 'flex', gap: '8px'}}>
                <button
                  onClick={() => alert('Voice input feature - would record short notes here!')}
                  style={{
                    flex: 1,
                    padding: '10px',
                    backgroundColor: '#16a34a',
                    color: 'white',
                    border: 'none',
                    borderRadius: '8px',
                    fontSize: '14px',
                    fontWeight: '600',
                    cursor: 'pointer'
                  }}
                >
                  🎤 Voice Note
                </button>
                
                <button
                  onClick={() => generateAIClinalNotes(sessionInput)}
                  disabled={!sessionInput.trim() || isGeneratingNotes}
                  style={{
                    flex: 1,
                    padding: '10px',
                    backgroundColor: (!sessionInput.trim() || isGeneratingNotes) ? '#9ca3af' : '#2563eb',
                    color: 'white',
                    border: 'none',
                    borderRadius: '8px',
                    fontSize: '14px',
                    fontWeight: '600',
                    cursor: (!sessionInput.trim() || isGeneratingNotes) ? 'not-allowed' : 'pointer'
                  }}
                >
                  {isGeneratingNotes ? '🤖 Generating...' : '🤖 Generate Notes'}
                </button>
              </div>
            </div>

            {/* AI Generated Notes */}
            {(aiNotes || isGeneratingNotes) && (
              <div style={{
                backgroundColor: 'white',
                borderRadius: '12px',
                padding: '16px',
                marginBottom: '16px',
                boxShadow: '0 2px 4px rgba(0,0,0,0.1)'
              }}>
                <div style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '12px'}}>
                  <h3 style={{margin: 0}}>🤖 AI Clinical Notes</h3>
                  {aiNotes && (
                    <button
                      onClick={() => downloadNotes(aiNotes, `clinical-notes-${Date.now()}.txt`)}
                      style={{
                        padding: '6px 12px',
                        backgroundColor: '#16a34a',
                        color: 'white',
                        border: 'none',
                        borderRadius: '6px',
                        fontSize: '12px',
                        cursor: 'pointer'
                      }}
                    >
                      📥 Download
                    </button>
                  )}
                </div>
                
                {isGeneratingNotes ? (
                  <div style={{
                    padding: '24px',
                    textAlign: 'center',
                    color: '#6b7280'
                  }}>
                    <p>🤖 Claude AI is generating your clinical notes...</p>
                    <p style={{fontSize: '14px'}}>This may take a moment.</p>
                  </div>
                ) : (
                  <div style={{
                    backgroundColor: '#f8fafc',
                    border: '1px solid #e2e8f0',
                    borderRadius: '8px',
                    padding: '16px',
                    fontFamily: 'monospace',
                    fontSize: '14px',
                    lineHeight: '1.6',
                    whiteSpace: 'pre-wrap',
                    maxHeight: '400px',
                    overflowY: 'auto'
                  }}>
                    {aiNotes}
                  </div>
                )}
              </div>
            )}
          </div>
        )}

        {activeTab === 'notifications' && (
          <div>
            <h2 style={{fontSize: '20px', fontWeight: 'bold', marginBottom: '16px'}}>Notifications</h2>
            
            <div style={{
              backgroundColor: '#fef3c7',
              borderRadius: '12px',
              padding: '16px',
              marginBottom: '16px',
              border: '1px solid #f59e0b'
            }}>
              <h3 style={{color: '#92400e', marginBottom: '8px'}}>🧪 Test System</h3>
              <p style={{color: '#92400e', fontSize: '14px', marginBottom: '12px'}}>
                Current notifications: {notifications.length}
              </p>
              <button
                onClick={testNotifications}
                style={{
                  width: '100%',
                  padding: '12px',
                  backgroundColor: '#8b5cf6',
                  color: 'white',
                  border: 'none',
                  borderRadius: '8px',
                  fontSize: '16px',
                  fontWeight: '600',
                  cursor: 'pointer'
                }}
              >
                📧📱 Add Test Notifications
              </button>
            </div>

            <div style={{
              backgroundColor: 'white',
              borderRadius: '12px',
              padding: '16px',
              boxShadow: '0 2px 4px rgba(0,0,0,0.1)'
            }}>
              <h3 style={{marginBottom: '16px'}}>Recent Activity</h3>
              {notifications.length === 0 ? (
                <p style={{textAlign: 'center', color: '#666', padding: '24px'}}>
                  No notifications yet. Click the test button above!
                </p>
              ) : (
                <div>
                  {notifications.map(notif => (
                    <div key={notif.id} style={{
                      padding: '12px',
                      backgroundColor: notif.type === 'email' ? '#f8fafc' : '#f0fdf4',
                      borderRadius: '8px',
                      marginBottom: '8px',
                      border: `1px solid ${notif.type === 'email' ? '#e2e8f0' : '#dcfce7'}`
                    }}>
                      <p style={{fontWeight: '500', margin: '0 0 4px 0'}}>{notif.message}</p>
                      <p style={{fontSize: '12px', color: '#666', margin: 0}}>{notif.time}</p>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}

        {activeTab === 'appointments' && (
          <div>
            <h2 style={{fontSize: '20px', fontWeight: 'bold', marginBottom: '16px'}}>📅 Appointments</h2>
            <p>Appointments feature coming soon...</p>
          </div>
        )}
      </div>

      {/* Bottom Navigation */}
      <div style={{
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'white',
        borderTop: '1px solid #e5e7eb',
        padding: '8px'
      }}>
        <div style={{display: 'flex', justifyContent: 'space-around'}}>
          {[
            {id: 'dashboard', label: 'Dashboard', icon: '📊'},
            {id: 'ai-notes', label: 'AI Notes', icon: '🤖'},
            {id: 'notifications', label: 'Notifications', icon: '🔔'},
            {id: 'appointments', label: 'Appointments', icon: '📅'}
          ].map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              style={{
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                padding: '8px',
                border: 'none',
                background: 'none',
                cursor: 'pointer',
                color: activeTab === tab.id ? '#2563eb' : '#666'
              }}
            >
              <span style={{fontSize: '20px', marginBottom: '4px'}}>{tab.icon}</span>
              <span style={{fontSize: '12px'}}>{tab.label}</span>
            </button>
          ))}
        </div>
      </div>

      {/* Side Menu */}
      {isMobileMenuOpen && (
        <div style={{
          position: 'fixed',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          backgroundColor: 'rgba(0,0,0,0.5)',
          zIndex: 50
        }} onClick={() => setIsMobileMenuOpen(false)}>
          <div style={{
            width: '280px',
            height: '100%',
            backgroundColor: 'white',
            padding: '0'
          }} onClick={e => e.stopPropagation()}>
            
            <div style={{
              padding: '24px',
              borderBottom: '1px solid #e5e7eb',
              backgroundColor: '#f8fafc'
            }}>
              <div style={{display: 'flex', alignItems: 'center', gap: '12px'}}>
                <div style={{
                  width: '48px',
                  height: '48px',
                  backgroundColor: '#2563eb',
                  borderRadius: '50%',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  color: 'white'
                }}>
                  <UserIcon />
                </div>
                <div>
                  <h3 style={{margin: 0, fontWeight: '600'}}>{currentUser.name}</h3>
                  <p style={{margin: 0, fontSize: '14px', color: '#666', textTransform: 'capitalize'}}>
                    {currentUser.role}
                  </p>
                </div>
              </div>
            </div>

            <nav style={{padding: '16px'}}>
              {[
                {id: 'dashboard', label: 'Dashboard', icon: '📊'},
                {id: 'ai-notes', label: 'AI Notes', icon: '🤖'},
                {id: 'notifications', label: 'Notifications', icon: '🔔'},
                {id: 'appointments', label: 'Appointments', icon: '📅'}
              ].map(item => (
                <button
                  key={item.id}
                  onClick={() => {
                    setActiveTab(item.id);
                    setIsMobileMenuOpen(false);
                  }}
                  style={{
                    width: '100%',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '12px',
                    padding: '12px',
                    border: 'none',
                    background: activeTab === item.id ? '#dbeafe' : 'transparent',
                    borderRadius: '8px',
                    marginBottom: '4px',
                    cursor: 'pointer',
                    fontSize: '16px',
                    color: activeTab === item.id ? '#2563eb' : '#374151'
                  }}
                >
                  <span style={{fontSize: '20px'}}>{item.icon}</span>
                  <span style={{fontWeight: '500'}}>{item.label}</span>
                </button>
              ))}
            </nav>

            <div style={{
              position: 'absolute',
              bottom: 0,
              left: 0,
              right: 0,
              padding: '16px',
              borderTop: '1px solid #e5e7eb'
            }}>
              <button
                onClick={() => {
                  setCurrentUser(null);
                  setIsMobileMenuOpen(false);
                }}
                style={{
                  width: '100%',
                  padding: '12px',
                  backgroundColor: '#ef4444',
                  color: 'white',
                  border: 'none',
                  borderRadius: '8px',
                  fontSize: '16px',
                  fontWeight: '500',
                  cursor: 'pointer'
                }}
              >
                🚪 Logout
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
